[build-system]
requires = ["setuptools>=46.4"]
build-backend = "setuptools.build_meta"

[project]
name = "ewoksppf"
version = "3.1.0rc1"
authors = [{ name = "ESRF", email = "dau-pydev@esrf.fr" }]
description = "Pypushflow binding for Ewoks"
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE.md" }
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.8"
dependencies = [
    "ewokscore >=5.0.0",
    "pypushflow >=2.1.0rc1",
]

[project.urls]
Homepage = "https://github.com/ewoks-kit/ewoksppf/"
Documentation = "https://ewoksppf.readthedocs.io/"
Repository = "https://github.com/ewoks-kit/ewoksppf/"
Issues = "https://github.com/ewoks-kit/ewoksppf/issues"
Changelog = "https://github.com/ewoks-kit/ewoksppf/blob/main/CHANGELOG.md"

[project.optional-dependencies]
test = [
    "pytest >=7",
]
dev = [
    "ewoksppf[test]",
    "ruff>=0.16.0",
]
doc = [
    "ewoksppf[test]",
    "sphinx >=4.5",
    "sphinxcontrib-mermaid >=0.7",
    "sphinx-autodoc-typehints >=1.16",
    "pydata-sphinx-theme",
    "sphinx-copybutton",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.coverage.run]
omit = ['*/tests/*']

[project.entry-points."ewoks.engines"]
"ppf" = "ewoksppf.engine:PpfWorkflowEngine"

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "F", # pyflakes
    "I", # isort
    "S", # flake8-bandit
]
ignore = [
    "E501", # line too long
]

[tool.ruff.lint.per-file-ignores]
"src/ewoksppf/tests/*.py" = [
    "S101"  # allow asserts
]

[tool.ruff.lint.isort]
force-single-line = true
known-first-party = ["ewoksppf"]
